version: "3.9"
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./data:/data
      - ./log:/var/log
    environment:
      FLASK_DEBUG: False
    networks:
      - vnc-network
    restart: unless-stopped